### ISSUE TITLE
Unable to build/run from master

### ISSUE THREAD

**Issue by dst3p** [rstedman/tfs-pullrequest-dashboard#25]
I've forked the repository, and have followed the steps outlined in the ReadMe, however I was unable to successfully execute `npm run start` due to the following error:

````bash
[08:46:54] 'test' errored after 1.05 min
[08:46:54] Error: 1
at formatError (C:\_source\VSTS_Extensions\tfs-pullrequest-dashboard\node_modules\gulp\bin\gulp.js:169:10)
at Gulp.<anonymous> (C:\_source\VSTS_Extensions\tfs-pullrequest-dashboard\node_modules\gulp\bin\gulp.js:195:15)
at emitOne (events.js:116:13)
at Gulp.emit (events.js:211:7)
at Gulp.Orchestrator._emitTaskDone (C:\_source\VSTS_Extensions\tfs-pullrequest-dashboard\node_modules\orchestrator\index.js:264:8)
at C:\_source\VSTS_Extensions\tfs-pullrequest-dashboard\node_modules\orchestrator\index.js:275:23
at finish (C:\_source\VSTS_Extensions\tfs-pullrequest-dashboard\node_modules\orchestrator\lib\runTask.js:21:8)
at cb (C:\_source\VSTS_Extensions\tfs-pullrequest-dashboard\node_modules\orchestrator\lib\runTask.js:29:3)
at Timeout.removeAllListeners [as _onTimeout] (C:\_source\VSTS_Extensions\tfs-pullrequest-dashboard\node_modules\karma\lib\server.js:380:7)
at ontimeout (timers.js:498:11)
at tryOnTimeout (timers.js:323:5)
at Timer.listOnTimeout (timers.js:290:5)
````

Commenting out the `test` function in the gulp file allowed compile

````js
gulp.task('test', function(callback) {
    // new karma.Server({
    //     configFile: __dirname + '/karma.conf.js',
    //     singleRun: true
    // }, callback).start();
});
````

However, I'm still unable to start the service. Any help would be appreciated. I've updated the dev fields in `appConfig.service.ts` as indicated in the readme

![image](https://user-images.githubusercontent.com/1471089/45555590-d0f39280-b7fe-11e8-91e7-7d8a82d12968.png)

Thanks!

**Comment by rstedman** [comment]
Some questions:
- What OS are you running?
- Can you try the following change to the gulpfile - the compile task is defined as:
```
gulp.task('compile', ['copy:vendor', 'bundle:vendor', 'compile:sources', 'test']);
```
remove the test task, so that the line looks like:
```
gulp.task('compile', ['copy:vendor', 'bundle:vendor', 'compile:sources']);
```
then try running `npm run start` again.  Does it actually start serving?

**Comment by dst3p** [comment]
No worries! Thanks for getting back to me. I'm running this on Windows 10. I'll try running this today with the changes you've requested and report back.

**Comment by dst3p** [comment]
Sweet, that worked! Thank you. Now just have to get past a CORS issue in the browser.
